AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation template for Grocery Heaven development environment v20171030"

Resources: 
  DbSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "DB subnet group for development environment"
      DBSubnetGroupName: db-subnet-group-uw2-dev-001
      SubnetIds:
        - "subnet-817ecfca"
        - "subnet-ba8116c3"
        - "subnet-714c252b"
  
  #DbSecurityGroup:
  #  Type: "AWS::RDS::DBSecurityGroup"
  #  Properties:
  #    GroupDescription: "DB security group for development environment"
  #    EC2VpcId: "vpc-badfe8c3"
  #    DBSecurityGroupIngress:
  #      - EC2SecurityGroupId: sg-0541b69472d479c3e

  DbInstanceProductMaster:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: 20
      AvailabilityZone: us-west-2a
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: rds-uw2a-pd-dev-002
      DBName: db_product
      DBSubnetGroupName: !Ref 'DbSubnetGroup'
      Engine: MySQL
      EngineVersion: 5.7.19
      MasterUsername: root
      MasterUserPassword: rmfhtjflgpqms2018$
      Port: 3306
      PubliclyAccessible: false
      VPCSecurityGroups: 
        - sg-0541b69472d479c3e
