AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation template for Grocery Heaven development environment v20171030"

Resources: 
  RdsSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "DB subnet group for development environment"
      DBSubnetGroupName: rds-subnet-group-uw2-dev
      SubnetIds:
        - "subnet-817ecfca"
        - "subnet-ba8116c3"
        - "subnet-714c252b"
  
  RdsEc2SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "DB security group for development environment"
      SecurityGroupIngress:
        EC2SecurityGroupName: sgdevdbgroups

  RdsProductMasterDb:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: 20
      AvailabilityZone: us-west-2a
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: rds-uw2a-product-dev-001
      DBName: db_product
      DBSubnetGroupName: !Ref 'RdsSubnetGroup'
      Engine: MySQL
      EngineVersion: 5.7.19
      MasterUsername: root
      MasterUserPassword: rmfhtjflgpqms2018$
      Port: 3306
      PubliclyAccessible: false
      VPCSecurityGroups:
        - !Ref sgdevdbgroup

