AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation template for Grocery Heaven development environment v20171030"

Resources: 
  DbSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "DB subnet group for development environment"
      DBSubnetGroupName:
      SubnetIds:
      Tags:
        - Key: "Name"
          Value: "db-subnet-group-uw2-dev"
  
  DbSecurityGroup:
    Type: "AWS::RDS::DBSecurityGroup"
    Properties:
      DBSecurityGroupIngress:
        EC2SecurityGroupName: sg-0541b69472d479c3e

  ProductMasterDb:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: 20
      AvailabilityZone: us-west-2a
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: rds-uws2a-product-dev-001
      DBName: db_product
      DBSecurityGroups: !Ref 'DbSecurityGroup'
      DBSubnetGroupName: !Ref 'DbSubnetGroup'
      Engine: MySQL
      EngineVersion: 5.7.19
      MasterUsername: root
      MasterUserPassword: rmfhtjflgpqms2018$
      MonitoringInterval: 60
      Port: 3306
      PubliclyAccessible: false
      VPCSecurityGroups:

Outputs:
  EndPointAddress:
    Description: "Product master database endpoint address"
    Value:
  EndPointPort:
    Description: "Product master database endpoint port"
    Value:
